/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "config.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(schema_ContainerCollectorConfig, schema_ContainerCollectorConfig, AUTO)


PB_BIND(schema_ExecuteCollectorConfig, schema_ExecuteCollectorConfig, AUTO)


PB_BIND(schema_MemExecCollectorConfig, schema_MemExecCollectorConfig, AUTO)


PB_BIND(schema_ConfigurationRequest, schema_ConfigurationRequest, AUTO)


PB_BIND(schema_ConfigurationResponse, schema_ConfigurationResponse, AUTO)




